### ISSUE TITLE
Configuration invalid? File contains no section headers.

### ISSUE THREAD

**Issue by DaveJarvis** [vmiklos/ged2dot#5]
Rename the attached file from `.ged.txt` to `.ged`.

```
./ged2dot.py ../My-Family-14-Jan-2016.ged 
Configuration invalid? File contains no section headers.
file: '../My-Family-14-Jan-2016.ged', line: 1
'0 HEAD\n'
Traceback (most recent call last):
  File "./ged2dot.py", line 873, in main
    config = Config(sys.argv[1:])
  File "./ged2dot.py", line 816, in __init__
    self.parse()
  File "./ged2dot.py", line 834, in parse
    self.parser.read(path)
  File "/usr/lib/python3.4/configparser.py", line 672, in read
    self._read(fp, filename)
  File "/usr/lib/python3.4/configparser.py", line 1058, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '../My-Family-14-Jan-2016.ged', line: 1
'0 HEAD\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ged2dot.py", line 889, in <module>
    main()
  File "./ged2dot.py", line 876, in main
    config.usage()
UnboundLocalError: local variable 'config' referenced before assignment
```

[My-Family-14-Jan-2016.ged.txt](https://github.com/vmiklos/ged2dot/files/90997/My-Family-14-Jan-2016.ged.txt)

File loads fine using LibreOffice extension.

**Comment by vmiklos** [comment]
That's a non-issue. :-)

ged2dot either expects a `ged2dotrc` file in the current directory, or expects that the first parameter of the script is the path to such a configuration file -- i.e. you should pass a configuration file to the script, not an actual `.ged` file.
The LibreOffice extension generates a default configuration file on the fly for you, that's why it worked there.
See `test/screenshotrc` in the repo, if you copy that as ged2dotrc and replace screenshot.ged with your actual .ged file, then it should be fine.
If touching Python code is not a problem for you, then maybe send a pull request that adds a --help switch to the script, so that the above details are properly documented. :-)
Does that help?

**Comment by DaveJarvis** [comment]
https://en.wikipedia.org/wiki/Principle_of_least_astonishment

I used a different solution.
